Test for #1507: Backend error:"cannot find symbol" caused by spurious final local variable used for assignment outside of its scope
Test passes, perhaps due to recent fixes in Scope subclasses that had hashCode missing and not corresponding to
their equals() implementation. Since substitutions are keyed by Scope it is possible that rehashing issues
was the problem.